# Generated by Django 5.0.1 on 2024-02-26 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_basket_profile_alter_basket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='api.profile'),
        ),
    ]
